### PR TITLE
Prompt for projectName if unable to derive from dir

### LINKED ISSUE #164: Vue app creation failing
I'm having trouble creating a vue project using create-single-spa.

Looks like if I try to use the current dir for the project, then it uses '.' as the project name which gets rejected as an invalid name

```
# create-single-spa
(node:14199) ExperimentalWarning: The fs.promises API is experimental
? Directory for new project .
? Select type to generate single-spa application / parcel
? Which framework do you want to use? vue
? Organization name (use lowercase and dashes) en
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: projectName must use lowercase and dashes!
    at SingleSpaVueGenerator.runVueCli (/root/.nvm/versions/node/v10.15.3/lib/node_modules/create-single-spa/node_modules/generator-single-spa/src/vue/generator-single-spa-vue.js:55:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at Immediate.setImmediate (/root/.nvm/versions/node/v10.15.3/lib/node_modules/create-single-spa/node_modules/yeoman-generator/lib/index.js:1007:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
#
```

If I go up a dir and point into the folder, it passes the projectName check but then just exits without setting up the project

```
# create-single-spa
(node:2439) ExperimentalWarning: The fs.promises API is experimental
? Directory for new project reporting
? Select type to generate single-spa application / parcel
? Which framework do you want to use? vue
? Organization name (use lowercase and dashes) en
#
```

### PR DESCRIPTION
**Pull request by filoxo**
Resolves #164 

To test, I ran the following variations using the cli (along with selecting Vue as the framework):
- `create-single-spa .` (prompts for projectName, generates in current directory)
- `create-single-spa ..`  (prompts for projectName, generates in parent directory)
- `create-single-spa reporting` (derives projectName, generates in current directory)
- `create-single-spa ./reporting` (derives projectName, generates in current directory)
- `create-single-spa ../reporting` (derives projectName, generates in parent directory)

### CODE REVIEW

File: packages/generator-single-spa/src/vue/generator-single-spa-vue.js [hunk 1]
```diff
@@ -31,6 +35,30 @@ module.exports = class SingleSpaVueGenerator extends Generator {
         console.log(chalk.red("orgName must use lowercase and dashes!"));
       this.options.orgName = orgName;
     }
+
+    let { dir, name } = path.parse(this.options.dir);
+
+    if (!isValidName(name)) {
+      while (!this.options.projectName) {
```
Comment (joeldenning) [inline packages/generator-single-spa/src/vue/generator-single-spa-vue.js:42]: I like this - give the user more chances to correctly provide a projectName
